name: Sync Helm Charts to Alibaba Cloud ACR

on:
  push:
    branches: [ main ]
    paths:
      - 'charts-to-sync.txt'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install oras
        run: |
          wget https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz -O oras.tar.gz
          mkdir -p oras-install/
          tar -zxf oras.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras.tar.gz oras-install/
          oras version
      
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Login to Alibaba Cloud ACR
        run: |
          echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login ${{ secrets.ALIYUN_REGISTRY_ENDPOINT }} -u ${{ secrets.ALIYUN_REGISTRY_USER }} --password-stdin
      
      - name: Validate config file
        run: |
          if [ ! -f "charts-to-sync.txt" ]; then
            echo "Error: charts-to-sync.txt not found!"
            exit 1
          fi
          
          if [ ! -s "charts-to-sync.txt" ]; then
            echo "Error: charts-to-sync.txt is empty!"
            exit 1
          fi
          
          while IFS= read -r line; do
            if [[ -z "$line" || "$line" == \#* ]]; then
              continue
            fi
            
            # 更灵活的验证规则
            if ! echo "$line" | grep -qE '^([^/]+/)?[^/]+/[^:]+:[^:]+$'; then
              echo "Error: Invalid format in charts-to-sync.txt: $line"
              echo "Expected format: [registry/]namespace/chart:version"
              exit 1
            fi
          done < charts-to-sync.txt
          
          echo "Config file validation passed"
      
      - name: Sync Helm Charts with oras
        env:
            ALIYUN_REGISTRY_ENDPOINT: ${{ secrets.ALIYUN_REGISTRY_ENDPOINT }}
            ALIYUN_NAMESPACE: ${{ secrets.ALIYUN_NAMESPACE }}
        run: |
          sync_errors=0
          
          while IFS= read -r source_line; do
            if [[ -z "$source_line" || "$source_line" == \#* ]]; then
              continue
            fi
            
            # 修正源镜像格式
            source_image="${source_line/registry-1.docker.io/docker.io}"
            
            chart_name=$(echo "$source_image" | awk -F'/' '{print $NF}' | awk -F':' '{print $1}')
            version=$(echo "$source_image" | awk -F':' '{print $NF}')
            
            # 构建目标镜像地址
            target_image="${ALIYUN_REGISTRY_ENDPOINT}/${ALIYUN_NAMESPACE}/${chart_name}:${version}"
            
            echo "Syncing oci://${source_image} to oci://${target_image}"
            
            # 使用 oras 复制
            if ! oras copy "oci://${source_image}" "oci://${secrets.ALIYUN_REGISTRY_ENDPOINT}/${secrets.ALIYUN_NAMESPACE}/${chart_name}:${version}"; then
              echo "Error: Failed to sync ${source_image}"
              sync_errors=$((sync_errors + 1))
            else
              echo "Successfully synced ${source_image}"
            fi
            
            echo "-----------------------------------"
          done < charts-to-sync.txt
          
          if [ $sync_errors -gt 0 ]; then
            exit 1
          fi
