name: Sync DolphinScheduler Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts-to-sync.txt'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up crane
        run: |
          wget https://github.com/google/go-containerregistry/releases/download/v0.15.3/crane_0.15.3_linux_amd64 -O crane
          chmod +x crane
          sudo mv crane /usr/local/bin/

      - name: Login to Alibaba Cloud ACR
        run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login ${{ secrets.ALIYUN_REGISTRY_ENDPOINT }} -u ${{ secrets.ALIYUN_REGISTRY_USER }} --password-stdin

      - name: Sync Helm Charts from Config File
        run: |
          while IFS= read -r source_image; do
            # 提取chart名称和版本
            chart_name=$(echo "$source_image" | awk -F'/' '{print $NF}' | awk -F':' '{print $1}')
            version=$(echo "$source_image" | awk -F':' '{print $NF}')
            
            # 同步到ACR
            crane copy \
              "oci://$source_image" \
              "oci://${{ secrets.ALIYUN_REGISTRY_ENDPOINT }}/${{ secrets.ALIYUN_NAMESPACE }}/${chart_name}:${version}"
            
            echo "Synced $source_image to ACR"
          done < charts-to-sync.txt
